//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoAziendali
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anagrafica
    {
        public System.Guid IdAnagrafica { get; set; }
        public string Cognome { get; set; }
        public string Nome { get; set; }
        public Nullable<int> IdSocieta { get; set; }
        public Nullable<int> IdBusinessUnit { get; set; }
    }
}
