//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoAziendali
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarDbEntities : DbContext
    {
        public CarDbEntities()
            : base("name=CarDbEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnagraficaVecchia> AnagraficaVecchia { get; set; }
        public virtual DbSet<BusinessUnit> BusinessUnit { get; set; }
        public virtual DbSet<CausaliManutenzione> CausaliManutenzione { get; set; }
        public virtual DbSet<CommesseVecchia> CommesseVecchia { get; set; }
        public virtual DbSet<Documenti> Documenti { get; set; }
        public virtual DbSet<Email> Email { get; set; }
        public virtual DbSet<Fornitori> Fornitori { get; set; }
        public virtual DbSet<ManutenzioniVeicoli> ManutenzioniVeicoli { get; set; }
        public virtual DbSet<Modalita> Modalita { get; set; }
        public virtual DbSet<Pedaggi> Pedaggi { get; set; }
        public virtual DbSet<Province> Province { get; set; }
        public virtual DbSet<Scadenze> Scadenze { get; set; }
        public virtual DbSet<ScadenzeVeicoli> ScadenzeVeicoli { get; set; }
        public virtual DbSet<Societa> Societa { get; set; }
        public virtual DbSet<Stati> Stati { get; set; }
        public virtual DbSet<StatoVeicoli> StatoVeicoli { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TelepassViacard> TelepassViacard { get; set; }
        public virtual DbSet<UtilizzoVeicoli> UtilizzoVeicoli { get; set; }
        public virtual DbSet<Veicoli> Veicoli { get; set; }
    }
}
