//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoAziendali
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommesseVecchia
    {
        public int IdCommessa { get; set; }
        public string Commessa { get; set; }
        public Nullable<int> IdSocieta { get; set; }
        public Nullable<int> IdBusinessUnit { get; set; }
    
        public virtual BusinessUnit BusinessUnit { get; set; }
        public virtual Societa Societa { get; set; }
    }
}
