//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoAziendali
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManutenzioniVeicoli
    {
        public int IdManutenzioneVeicoli { get; set; }
        public System.DateTime Data { get; set; }
        public int IdVeicolo { get; set; }
        public int IdCausaleManutenzione { get; set; }
        public string Note { get; set; }
        public int IdFornitore { get; set; }
        public decimal Costo { get; set; }
        public Nullable<int> IdDocumento { get; set; }
    
        public virtual CausaliManutenzione CausaliManutenzione { get; set; }
        public virtual Documenti Documenti { get; set; }
        public virtual Fornitori Fornitori { get; set; }
        public virtual Veicoli Veicoli { get; set; }
    }
}
