//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoAziendali
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedaggi
    {
        public int IdPedaggi { get; set; }
        public string TelepassViacard { get; set; }
        public Nullable<int> Mese { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Percorso { get; set; }
        public string Classe { get; set; }
        public Nullable<decimal> Costo { get; set; }
    }
}
