//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoAziendali
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scadenze
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Scadenze()
        {
            this.ScadenzeVeicoli = new HashSet<ScadenzeVeicoli>();
        }
    
        public int IdScadenza { get; set; }
        public string Scadenza { get; set; }
        public Nullable<int> GiorniPreavviso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScadenzeVeicoli> ScadenzeVeicoli { get; set; }
    }
}
