//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoAziendali
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScadenzeVeicoli
    {
        public int IdScadenzeVeicoli { get; set; }
        public int IdVeicolo { get; set; }
        public System.DateTime Data { get; set; }
        public int IdScadenza { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<int> IdDocumento { get; set; }
        public string Note { get; set; }
        public Nullable<bool> Avviso { get; set; }
        public Nullable<bool> AvvisoInviato { get; set; }
    
        public virtual Documenti Documenti { get; set; }
        public virtual Scadenze Scadenze { get; set; }
        public virtual Veicoli Veicoli { get; set; }
    }
}
