//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoAziendali
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatoVeicoli
    {
        public int IdStatoVeicolo { get; set; }
        public int IdVeicolo { get; set; }
        public Nullable<int> IdProprieta { get; set; }
        public Nullable<int> IdLibretto { get; set; }
        public Nullable<int> IdTelepass { get; set; }
        public Nullable<int> IdViacard { get; set; }
        public System.DateTime Data { get; set; }
        public int IdStato { get; set; }
        public Nullable<int> ChilometriRental { get; set; }
        public int IdSocieta { get; set; }
        public Nullable<int> IdBusinessUnit { get; set; }
        public int IdModalita { get; set; }
        public string Note { get; set; }
        public Nullable<System.Guid> IdAnagrafica { get; set; }
    
        public virtual BusinessUnit BusinessUnit { get; set; }
        public virtual Documenti Documenti { get; set; }
        public virtual Documenti Documenti1 { get; set; }
        public virtual Modalita Modalita { get; set; }
        public virtual Societa Societa { get; set; }
        public virtual Stati Stati { get; set; }
        public virtual TelepassViacard TelepassViacard { get; set; }
        public virtual TelepassViacard TelepassViacard1 { get; set; }
        public virtual Veicoli Veicoli { get; set; }
    }
}
