//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoAziendali
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veicoli
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Veicoli()
        {
            this.ManutenzioniVeicoli = new HashSet<ManutenzioniVeicoli>();
            this.ScadenzeVeicoli = new HashSet<ScadenzeVeicoli>();
            this.StatoVeicoli = new HashSet<StatoVeicoli>();
            this.UtilizzoVeicoli = new HashSet<UtilizzoVeicoli>();
        }
    
        public int IdVeicolo { get; set; }
        public string Targa { get; set; }
        public string Marca { get; set; }
        public string Modello { get; set; }
        public string Versione { get; set; }
        public string Telaio { get; set; }
        public Nullable<System.DateTime> Immatricolazione { get; set; }
        public Nullable<int> Cilindrata { get; set; }
        public Nullable<int> CvVapore { get; set; }
        public Nullable<int> Kw { get; set; }
        public Nullable<int> CvFiscali { get; set; }
        public string Colore { get; set; }
        public string Formato { get; set; }
        public string Alimentazione { get; set; }
        public string NormativaEuro { get; set; }
        public string Provincia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManutenzioniVeicoli> ManutenzioniVeicoli { get; set; }
        public virtual Province Province { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScadenzeVeicoli> ScadenzeVeicoli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatoVeicoli> StatoVeicoli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UtilizzoVeicoli> UtilizzoVeicoli { get; set; }
    }
}
